{
 "title": "ECS Metrics",
 "description": "using Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div style=\"text-align: center; font-size: 32px\">These are the application-level metrics</div>"
  },
  {
   "title": "Get Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_total{job=\"ecs-metrics\",method=\"get\"}"
    }
   ]
  },
  {
   "title": "Post Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_total{job=\"ecs-metrics\",method=\"post\"}"
    }
   ]
  },
  {
   "title": "Put Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_total{job=\"ecs-metrics\",method=\"put\"}"
    }
   ]
  },
  {
   "title": "Delete Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_total{job=\"ecs-metrics\",method=\"delete\"}"
    }
   ]
  }
 ]
}