version: '3.1'
services:
  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'todo'
      MYSQL_USER: 'todo-app'
      MYSQL_PASSWORD: '0000'
    ports:
      - 3318:3306
    # Change this to your local path
    volumes:
      - dbvolume:/var/lib/mysql

volumes:
  dbvolume: