global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
  - job_name: 'ecs-metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-target-1:80']
